name: image-scan
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      image:
        description: "Image to Scan"
        required: true
        type: string
      sha:
        description: "Image SHA"
        required: true
        type: string
      blue:
        description: "foo"
        required: false
        type: string
jobs: 
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: us-east-2
          role-to-assume: arn:aws:iam::821194404822:role/kms-write
          disable-retry: true
        continue-on-error: true

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Scan image
        uses: anchore/scan-action@v3
        id: scan
        with:
          image: ${{ inputs.image }}

      - name: Inspect action SARIF report
        run: cat ${{ steps.scan.outputs.sarif }}
        if: ${{ always() }}

      # - name: Keyless signing of image
      #   run: |
      #     echo ${{ inputs.image }}
      #     cosign sign --tlog-upload=false --key awskms:///arn:aws:kms:us-east-2:821194404822:alias/grype ${{ inputs.image }}

      # - name: Verify the image signing
      #   run: |
      #     cosign verify --insecure-ignore-tlog --key awskms:///arn:aws:kms:us-east-2:821194404822:alias/grype ${{ inputs.image }} | jq .
      
