name: image-scan
# Changed 'on' to enable this workflow to be called from other workflows
on:
  workflow_call:
    # Introduced 'inputs' to define parameters that can be passed when calling this workflow
    inputs:
      image:
        description: "Image Name"
        required: true
        type: string
      sha:
        description: "Image SHA"
        required: true
        type: string
      
jobs: 
  build:
    runs-on: ubuntu-latest

    steps: 
      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      
      - name: Scan image
        uses: anchore/scan-action@v3
        with:
          image: ${{ inputs.image }}:${{ inputs.sha }}
      
      - name: Install cosign
        uses: sigstore/cosign-installer@v3.5.0
        with:
          cosign-release: 'v2.2.4'

      - name: Keyless signing of image
        run: |
          echo ${{ steps.digest.outputs.image_sha }}
          cosign sign --yes --rekor-url "https://rekor.sigstore.dev/" ${{ inputs.sha }}

      - name: Verify the image signing
        run: |
          cosign verify  --rekor-url "https://rekor.sigstore.dev/" ${{ inputs.sha }} --certificate-identity "https://github.com/andrewl3wis/messing-with-cosign/.github/workflows/sign.yaml@refs/heads/main" --certificate-oidc-issuer "https://token.actions.githubusercontent.com" | jq .
      
